### ISSUE TITLE
Why the videos I downloaded are not automatically merged into one file

### ISSUE THREAD

**Issue by DifferentSparkler** [TheCaduceus/Multi-Cloud-Transfer-Tool#4] opened 2022-05-28 14:54 UTC
![image](https://user-images.githubusercontent.com/38945550/170830703-3e87e32b-25c6-4f0e-9c43-daaf348c9f5e.png)

[download] Downloading video 8 of 57
[youtube] kgEgOi32CE0: Downloading webpage
[youtube] kgEgOi32CE0: Downloading android player API JSON
[info] kgEgOi32CE0: Downloading 1 format(s): 303+251
[download] Destination: A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].f303.webm
[download] 100% of 406.72MiB in 01:41
[download] Destination: A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].f251.webm
[download] 100% of 19.21MiB in 00:08
[Merger] Merging formats into "A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].webm"
ERROR: Postprocessing: Conversion failed!
[download] Downloading video 9 of 57
[youtube] kPIzBRPezY4: Downloading webpage
[youtube] kPIzBRPezY4: Downloading android player API JSON
[info] kPIzBRPezY4: Downloading 1 format(s): 303+251
[download] Destination: Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].f303.webm
[download] 100% of 360.37MiB in 01:31
[download] Destination: Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].f251.webm
[download] 100% of 17.58MiB in 00:09
[Merger] Merging formats into "Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].webm"
ERROR: Postprocessing: Conversion failed!
[download] Downloading video 10 of 57
[youtube] oi38cQMORQY: Downloading webpage
[youtube] oi38cQMORQY: Downloading android player API JSON
[info] oi38cQMORQY: Downloading 1 format(s): 303+251
[download] Destination: The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].f303.webm
[download] 100% of 403.08MiB in 01:26
[download] Destination: The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].f251.webm
[download] 100% of 18.37MiB in 00:11
[Merger] Merging formats into "The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].webm"
ERROR: Postprocessing: Conversion failed!

Can I set the default to download the highest quality MP4 format file

**Comment by TheCaduceus** [comment] 2022-05-28 17:00
> ![image](https://user-images.githubusercontent.com/38945550/170830703-3e87e32b-25c6-4f0e-9c43-daaf348c9f5e.png)
> 
> [download] Downloading video 8 of 57 [youtube] kgEgOi32CE0: Downloading webpage [youtube] kgEgOi32CE0: Downloading android player API JSON [info] kgEgOi32CE0: Downloading 1 format(s): 303+251 [download] Destination: A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].f303.webm [download] 100% of 406.72MiB in 01:41 [download] Destination: A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].f251.webm [download] 100% of 19.21MiB in 00:08 [Merger] Merging formats into "A pot of wine among watermelon fields.So…The life of watermelons and grapes瓜间一壶酒，西瓜和葡萄的一生？丨Liziqi [kgEgOi32CE0].webm" ERROR: Postprocessing: Conversion failed! [download] Downloading video 9 of 57 [youtube] kPIzBRPezY4: Downloading webpage [youtube] kPIzBRPezY4: Downloading android player API JSON [info] kPIzBRPezY4: Downloading 1 format(s): 303+251 [download] Destination: Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].f303.webm [download] 100% of 360.37MiB in 01:31 [download] Destination: Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].f251.webm [download] 100% of 17.58MiB in 00:09 [Merger] Merging formats into "Finally, a different title! “The life of okra and bamboo fence, LOL这次可算有点不一样的标题了！秋葵，和竹筒路的一生嘻嘻丨Liziqi [kPIzBRPezY4].webm" ERROR: Postprocessing: Conversion failed! [download] Downloading video 10 of 57 [youtube] oi38cQMORQY: Downloading webpage [youtube] oi38cQMORQY: Downloading android player API JSON [info] oi38cQMORQY: Downloading 1 format(s): 303+251 [download] Destination: The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].f303.webm [download] 100% of 403.08MiB in 01:26 [download] Destination: The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].f251.webm [download] 100% of 18.37MiB in 00:11 [Merger] Merging formats into "The life of cucumbers黄瓜的一生丨Liziqi Channel [oi38cQMORQY].webm" ERROR: Postprocessing: Conversion failed!
> 
> Can I set the default to download the highest quality MP4 format file

This problem seems to be caused by not giving required permission at destination! Program needs writing permission in destination for uploading final output. Error code indicates that downloaded files got merged but not got uploaded to destination. Please check if you given writing permission in Rclone config file. If error persist then you can contact yt-dlp creators because this project usage the latest yt-dlp version without any modification. and for getting video file is custom format like Mp4 you can write following as argument:
``--format mp4``

**Comment by DifferentSparkler** [comment] 2022-05-29 14:07
Thank you very much

**Closed** 2022-05-29 14:34 UTC
Labels: help wanted, question
